<!--
 ------
 BGA rps_rps.tpl for rps
 ------
-->

<!-- Custom SVG Definitions for cyberpunk icons -->
<svg style="display: none;">
    <defs>
        <!-- Rock Icon (Glowing Faceted Crystal Shield) -->
        <g id="icon-rock">
            <polygon points="12 2, 21 8, 17 20, 7 20, 3 8" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/>
            <polygon points="12 2, 16.5 9, 12 15, 7.5 9" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linejoin="round"/>
            <line x1="12" y1="15" x2="12" y2="20" stroke="currentColor" stroke-width="1.5"/>
            <line x1="7.5" y1="9" x2="3" y2="8" stroke="currentColor" stroke-width="1.5"/>
            <line x1="16.5" y1="9" x2="21" y2="8" stroke="currentColor" stroke-width="1.5"/>
        </g>
        
        <!-- Paper Icon (Glowing Cybernetic Scroll/Microchip Sheet) -->
        <g id="icon-paper">
            <rect x="4" y="3" width="16" height="18" rx="2" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"/>
            <path d="M8 7h8M8 11h8M8 15h4" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
            <rect x="14" y="14" width="2" height="2" rx="0.5" fill="currentColor"/>
            <circle cx="15" cy="7" r="1" fill="currentColor"/>
            <circle cx="15" cy="11" r="1" fill="currentColor"/>
        </g>

        <!-- Scissors Icon (Glowing Cyber crossed plasma shears) -->
        <g id="icon-scissors">
            <circle cx="6" cy="18" r="3" fill="none" stroke="currentColor" stroke-width="2"/>
            <circle cx="18" cy="18" r="3" fill="none" stroke="currentColor" stroke-width="2"/>
            <path d="M8.5 15.5L12 11.5M15.5 15.5L12 11.5" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
            <path d="M12 11.5L17 4M12 11.5L7 4" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
            <circle cx="12" cy="11.5" r="1" fill="currentColor"/>
        </g>

        <!-- Locked/Shadow Icon -->
        <g id="icon-lock">
            <rect x="5" y="11" width="14" height="10" rx="2" fill="none" stroke="currentColor" stroke-width="2"/>
            <path d="M12 15v2" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
            <path d="M8 11V7a4 4 0 0 1 8 0v4" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>
        </g>
    </defs>
</svg>

<div id="sg-game-wrapper">
    <div class="stars"></div>
    <div class="glow-overlay"></div>

    <!-- Active Waiting Overlay for synchronization -->
    <div id="sg-lock-overlay" class="overlay-lock">
        <div class="overlay-content">
            <div class="spinner"></div>
            <h3 id="sg-lock-title">TRANSMITTING DATA</h3>
            <p id="sg-lock-msg">Waiting for opponent to complete their action...</p>
        </div>
    </div>

    <!-- MAIN GAME AREA -->
    <div id="sg-main-container">
        
        <!-- PLAYER 1 SETUP SCREEN -->
        <div id="screen-p1-setup" class="sg-screen">
            <div class="sg-title-area">
                <span class="badge player1-badge">PLAYER 1 TURN</span>
                <h2>Deploy Your Gambits</h2>
                <p>Construct your tactical public and hidden lists.</p>
            </div>

            <div class="setup-grid">
                <!-- Public Gambit (L1-A) -->
                <div class="card glassmorphic setup-panel cyan-panel">
                    <h3 class="panel-header text-cyan">
                        Public Gambit <span class="math-term">($L1_A$)</span>
                        <span class="tooltip">Visible to Player 2</span>
                    </h3>
                    <div class="card-slots" id="p1-gambit-slots">
                        <!-- 5 slots generated by JS -->
                    </div>
                </div>

                <!-- Shadow Gambit (L1-B) -->
                <div class="card glassmorphic setup-panel purple-panel">
                    <h3 class="panel-header text-purple">
                        Shadow Gambit <span class="math-term">($L1_B$)</span>
                        <span class="tooltip">Hidden from Player 2</span>
                    </h3>
                    <div class="card-slots" id="p1-shadow-slots">
                        <!-- 5 slots generated by JS -->
                    </div>
                    
                    <div class="reveal-control-container">
                        <button id="btn-reveal-shadow" class="btn reveal-btn">
                            <span class="eye-icon">👁</span> HOLD TO REVEAL SHADOW
                        </button>
                    </div>
                </div>
            </div>

            <!-- Choice Selector Pad (P1) -->
            <div class="selector-pad-container" id="p1-selector-container">
                <div class="current-selection-info">
                    Selecting <span id="current-slot-label" class="highlight-text text-cyan">Public Slot 1</span>
                </div>
                <div class="selector-pad">
                    <button class="choice-btn sg-choice-btn" data-choice="rock" id="p1-choice-rock">
                        <svg viewBox="0 0 24 24"><use href="#icon-rock"></use></svg>
                        <span>ROCK</span>
                    </button>
                    <button class="choice-btn sg-choice-btn" data-choice="paper" id="p1-choice-paper">
                        <svg viewBox="0 0 24 24"><use href="#icon-paper"></use></svg>
                        <span>PAPER</span>
                    </button>
                    <button class="choice-btn sg-choice-btn" data-choice="scissors" id="p1-choice-scissors">
                        <svg viewBox="0 0 24 24"><use href="#icon-scissors"></use></svg>
                        <span>SCISSORS</span>
                    </button>
                </div>
            </div>

            <div class="action-bar central-actions">
                <button id="btn-p1-random" class="btn secondary-btn glow-cyan-btn">
                    <span>RANDOM GENERATE</span>
                </button>
                <button id="btn-p1-confirm" class="btn primary-btn glow-cyan" disabled>
                    <span>CONFIRM DEPLOYMENT</span>
                </button>
            </div>
        </div>

        <!-- PLAYER 2 COUNTER SCREEN -->
        <div id="screen-p2-setup" class="sg-screen">
            <div class="sg-title-area">
                <span class="badge player2-badge">PLAYER 2 TURN</span>
                <h2>Deploy Countermeasures</h2>
                <p>Observe the Public Gambit. Anticipate the Shadow.</p>
            </div>

            <div class="p2-board">
                <!-- Player 1 Intel Panels (Read Only) -->
                <div class="intel-wrapper">
                    <!-- L1-A Public Intel -->
                    <div class="card glassmorphic intel-panel cyan-panel">
                        <h3 class="panel-header text-cyan">P1 Public Gambit <span class="math-term">($L1_A$)</span></h3>
                        <div class="card-slots read-only" id="p2-intel-public">
                            <!-- 5 slots populated by JS -->
                        </div>
                    </div>

                    <!-- L1-B Shadow (Hidden Intel) -->
                    <div class="card glassmorphic intel-panel purple-panel shadow-intel">
                        <h3 class="panel-header text-purple">P1 Shadow Gambit <span class="math-term">($L1_B$)</span></h3>
                        <div class="card-slots read-only locked-slots" id="p2-intel-shadow">
                            <!-- 5 locked slots -->
                            <div class="card-slot locked"><svg viewBox="0 0 24 24"><use href="#icon-lock"></use></svg></div>
                            <div class="card-slot locked"><svg viewBox="0 0 24 24"><use href="#icon-lock"></use></svg></div>
                            <div class="card-slot locked"><svg viewBox="0 0 24 24"><use href="#icon-lock"></use></svg></div>
                            <div class="card-slot locked"><svg viewBox="0 0 24 24"><use href="#icon-lock"></use></svg></div>
                            <div class="card-slot locked"><svg viewBox="0 0 24 24"><use href="#icon-lock"></use></svg></div>
                        </div>
                    </div>
                </div>

                <!-- Player 2 Counter Slots (Input) -->
                <div class="card glassmorphic setup-panel magenta-panel">
                    <h3 class="panel-header text-magenta">Your Counter List <span class="math-term">($L2$)</span></h3>
                    <div class="card-slots" id="p2-counter-slots">
                        <!-- 5 slots generated by JS -->
                    </div>
                </div>
            </div>

            <!-- Choice Selector Pad (P2) -->
            <div class="selector-pad-container" id="p2-selector-container">
                <div class="current-selection-info">
                    Selecting <span id="p2-slot-label" class="highlight-text text-magenta">Counter Slot 1</span>
                </div>
                <div class="selector-pad">
                    <button class="choice-btn sg-choice-btn p2-choice" data-choice="rock" id="p2-choice-rock">
                        <svg viewBox="0 0 24 24"><use href="#icon-rock"></use></svg>
                        <span>ROCK</span>
                    </button>
                    <button class="choice-btn sg-choice-btn p2-choice" data-choice="paper" id="p2-choice-paper">
                        <svg viewBox="0 0 24 24"><use href="#icon-paper"></use></svg>
                        <span>PAPER</span>
                    </button>
                    <button class="choice-btn sg-choice-btn p2-choice" data-choice="scissors" id="p2-choice-scissors">
                        <svg viewBox="0 0 24 24"><use href="#icon-scissors"></use></svg>
                        <span>SCISSORS</span>
                    </button>
                </div>
            </div>

            <div class="action-bar central-actions">
                <button id="btn-p2-random" class="btn secondary-btn glow-purple-btn">
                    <span>RANDOM GENERATE</span>
                </button>
                <button id="btn-p2-confirm" class="btn primary-btn glow-purple" disabled>
                    <span>ENGAGE SHOWDOWN</span>
                </button>
            </div>
        </div>

        <!-- SHOWDOWN SCREEN -->
        <div id="screen-showdown" class="sg-screen">
            <div class="sg-title-area">
                <span class="badge showdown-badge">RESOLVING PROTOCOL</span>
                <h2>The Shadow Reveal</h2>
                <p>Comparing Player 1's Shadow list <span class="math-term">($L1_B$)</span> against Player 2's Counter list <span class="math-term">($L2$)</span>.</p>
                
                <div class="cryptography-badge-wrapper">
                    <span id="showdown-security-badge" class="security-badge badge-secure">🛡️ SECURE BGA RESOLUTION VALIDATED</span>
                </div>
            </div>

            <div class="showdown-arena">
                <!-- Scoreboard -->
                <div class="scoreboard glassmorphic">
                    <div class="score-team team-p1">
                        <div class="team-label" id="lbl-p1-score-team">P1 SHADOW</div>
                        <div class="score-number" id="score-p1">0</div>
                    </div>
                    <div class="score-divider">:</div>
                    <div class="score-team team-p2">
                        <div class="team-label" id="lbl-p2-score-team">P2 COUNTER</div>
                        <div class="score-number" id="score-p2">0</div>
                    </div>
                </div>

                <!-- 5 duel tracks -->
                <div class="duel-tracks" id="showdown-tracks">
                    <!-- Generated dynamically by JS -->
                </div>
            </div>
        </div>

    </div>
</div>
